---
- hosts: iiif-image-server
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  gather_facts: yes
  vars:
    project_name: iiif-image-server
    # These are used in the passenger-nginx-config role
    app_deploy_path: /iiif-image-server
    passenger_startup_file: lib/index.js

  roles:
    - role: dev-dummy-cert
    - role: passenger-nginx-install
    - role: passenger-nginx-config
    # - role: jp2
    - role: image-server

  post_tasks:
    - name: mkdir ~/.npm-global
      become: no
      file: path=~/.npm-global state=directory
    - name: npm config set prefix
      become: no
      shell: npm config set prefix '~/.npm-global'
    - name: update profile
      become: no
      lineinfile:
        dest: ~/.bash_profile
        line: export PATH=~/.npm-global/bin:$PATH
    - name: install nodemon
      become: no
      shell: npm i -g nodemon
